application:
    build: code
    volumes:
        - ./symfony:/var/www/symfony
    tty: true
    restart: always
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: user
        MYSQL_PASSWORD: root
# Mongo DB Values
#    image: mongo:3.0.8
#    ports:
#        - 27017:27017        
    restart: always
php:
    build: php-fpm
    ports:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
    restart: always
nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
    restart: always
